apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: notification
        image: alpine:latest
        script: |
          #!/bin/sh
          echo "Sync Successful"
      restartPolicy: Never
  backoffLimit: 5