apiVersion: batch/v1
kind: Job
metadata:
  generateName: notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: notification
        image: alpine:latest
        script: |
          #!/bin/sh
          echo "Sync Successful"
      restartPolicy: Never
  backoffLimit: 5