apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: notification
        image: alpine:latest
        command: ["echo", "Sync Successful"]
      restartPolicy: Never
  backoffLimit: 5