apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-02
  template:
    metadata:
      labels:
        app: app-02
    spec:
      containers:
      - name: blue-green
        image: ngochung1809/blue-green:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: html_name
          value: "app-v2.html"
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: app-02-svc
spec:
  type: NodePort
  selector:
    app: app-02
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000