apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-master
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:ngocHung2000/argocd-deployment-strategies.git
    targetRevision: master
    path: argocd-hands-on-gitops/applications/app-master
  project: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true