apiVersion: v1
kind: Secret
metadata:
  name: repo-blue-green
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: repo-blue-green
  project: cicd
  url: git@github.com:ngocHung2000/argocd-deployment-strategies.git
  sshPrivateKey: |
    PRIVATE_KEY
  insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"