apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-01
  template:
    metadata:
      labels:
        app: app-01
    spec:
      containers:
      - name: blue-green
        image: ngochung1809/blue-green:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: html_name
          value: "app-v1.html"
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: app-01-svc
spec:
  type: NodePort
  selector:
    app: app-01
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5000